local nnoremap = require("restacksyj.keymap").nnoremap
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

nnoremap("<leader>a", function()
	mark.add_file()
end)
nnoremap("<C-e>", function()
	ui.toggle_quick_menu()
end)

nnoremap("<C-m>", function()
	ui.nav_file(1)
end)
nnoremap("<C-n>", function()
	ui.nav_file(2)
end)
nnoremap("<C-b>", function()
	ui.nav_file(3)
end)
nnoremap("<C-t>", function()
	ui.nav_file(4)
end)
